on:
  push:
    branches: main

jobs:
  pulumi:
    runs-on: ubuntu-latest
    env:
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: yarn
      - run: curl -fsSL https://get.pulumi.com | sh
      - run: ~/.pulumi/bin/pulumi login --local
      - run: ~/.pulumi/bin/pulumi stack init gh
      - run: ~/.pulumi/bin/pulumi stack select gh
      - run: ~/.pulumi/bin/pulumi preview
