on:
  push:
    branches: main

jobs:
  pulumi:
    runs-on: ubuntu-latest
    steps:
      - run: curl -fsSL https://get.pulumi.com | sh
      - run: ~/.pulumi/bin/pulumi login --local
      - run: ~/.pulumi/bin/pulumi preview
